### ISSUE TITLE
[Bug]: Minecraft crashes on launch with mod enabled

### ISSUE THREAD

**Issue by GenericCherrySwitch** [someaddons/betterchunkloading#10]
### Describe the bug you're experiencing

Minecraft crashes during the initial start-up phase while this mod is installed, supposedly due to a mixin-related error.

### Reproducability

Launch the game with betterchunkloading enabled

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric 0.15.6

### Logs

https://gist.github.com/GenericCherrySwitch/cc7abf817409e7bcd28a74d89bc9c611

**Comment by someaddons** [comment]
fixed in 3.2
