### ISSUE TITLE
[Bug]: Dedicated Server Crash

### ISSUE THREAD

**Issue by dylanjkl** [someaddons/betterchunkloading#11]
### Describe the bug you're experiencing

A player seemingly (I assume) loaded a chunk and the whole server closed immediatly.

### Reproducability

Unknown. Presumably related to chunk loading.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/dylanjkl/b05285a78bb22808b6cb103f8e8a0ba2

**Comment by Tommeh1** [comment]
Can confirm
[crash-2024-01-27_10.03.56-server.txt](https://github.com/someaddons/betterchunkloading/files/14071774/crash-2024-01-27_10.03.56-server.txt)

**Comment by someaddons** [comment]
fixed in 3.3^^
