### ISSUE TITLE
[Bug]: Exception in server tick loop

### ISSUE THREAD

**Issue by Silverbolt666** [someaddons/betterchunkloading#12]
### Describe the bug you're experiencing

The crash seems to be related to the "betterchunkloading" mod. Specifically, it looks like an IllegalStateException is being thrown in the ConcurrentHashMap$BaseIterator.remove method at line 133 of the EventHandler class in the "betterchunkloading" mod (According to chat GPT).

There are two versions of this errors:
1) World does not load new chunks, having a kind of "eternal freeze", leaving and rejoining the world/game seems to temporarily fix the issue. Leaving the world keeps the game on "Saving World" screen for an invariable amount of time.

2) After 1) happened, game has a chance to freeze and crash.

Feel free to ask for more info :)

### Reproducability

The issue happens on chunk loading. 

Render distance at 64 chunks (doesn't matter the render distance, error persists despite changes on video settings).

Forge 47.2.20
Minecraft 1.20.1
Mod version: 3.2 (latest)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/Silverbolt666/9dbee3459fd4f8ca3979050705105f3a

**Comment by someaddons** [comment]
should be fixed in 3.3
