### ISSUE TITLE
[Bug]: BetterChunkLoading error is reported at server startup

### ISSUE THREAD

**Issue by xnhjs233** [someaddons/betterchunkloading#13]
### Describe the bug you're experiencing

BetterChunkLoading error is reported at server startup
It has been updated to version 3.3

### Reproducability

Start the server after putting the pre-mod and this mod into the mods folder

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/xnhjs233/cdc3c2cb9e9f414e0cc34c3e5eb30d2e

**Comment by someaddons** [comment]
that is normal/fine, the config change so it got an error on loading it and resets it. Gonna just happen once
