### ISSUE TITLE
Fabric 1.20.4 support

### ISSUE THREAD

**Issue by Zorklis** [someaddons/betterchunkloading#14]
### Describe the bug you're experiencing

 -

### Reproducability

 -

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.4

### Modloader version

Fabric

### Logs

-

**Comment by sternschnaube** [comment]
Any update on this @someaddons? 😊

**Comment by someaddons** [comment]
Next version will be 1.21, too much effort to support the small intermediary versions, which few ppl play and are already declining

**Comment by sternschnaube** [comment]
Good to know, thanks 😊
