### ISSUE TITLE
The mod being tagged as Forge/Fabric seems to cause it to not actually be seen as compatible with forge

### ISSUE THREAD

**Issue by amohacker** [someaddons/betterchunkloading#15]
This may not be the fault of the configuration, but in case it is hopefully this helps.
![image](https://github.com/someaddons/betterchunkloading/assets/23550096/44041222-a402-4fbf-a53f-62b47a586284)
![image](https://github.com/someaddons/betterchunkloading/assets/23550096/3f283b5f-2085-476f-8005-1fbeba1afff7)

**Comment by someaddons** [comment]
Clicking install on the main page causes it to install the last file uploaded, which is the fabric version in this case. To get the right loader select the right file on the website and click install on that, that'll work
