### ISSUE TITLE
[Bug]: Very weird visual glitches with Embeddium and Better Chunk Loading

### ISSUE THREAD

**Issue by BugmanBugman** [someaddons/betterchunkloading#16]
### Describe the bug you're experiencing

As reported here: https://github.com/embeddedt/embeddium/issues/193

### Reproducability

Have Embeddium and Better Chunk Loading in a world, watch as the world is rendered weird.
![image](https://github.com/someaddons/betterchunkloading/assets/40730042/964e7379-f70e-411c-9a79-21484e1da222)
![image](https://github.com/someaddons/betterchunkloading/assets/40730042/335f8ecb-ca08-4d10-8353-b8890f59c606)
![image](https://github.com/someaddons/betterchunkloading/assets/40730042/55a48453-6cd7-4d06-a13d-0fddd484fe88)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

None required

**Comment by someaddons** [comment]
better chunk loading only changes a bit in which priority chunks are loaded, if a client sided mod fails to display them its on the mod, report to embeddium again :)
