### ISSUE TITLE
Game occasionally lags out with this mod installed

### ISSUE THREAD

**Issue by switchmaxfx** [someaddons/betterchunkloading#17]
Recently since installing this mod my game has lagged out numerous times. All mobs freezing etc. Its only been happening since I've had this mod installed. These are the mods I have installed currently. https://i.imgur.com/hWOGR5N.png

**Comment by BigPhobos** [comment]
Can confirm, world often timed out at intermittent intervals while this mod was installed. Problems stopped after removing.
Tested on 1.20.1 with Fabric 0.15.7 and Quilt 0.24.0

**Comment by someaddons** [comment]
should be fixed in 4.0 afaik it was caused by some unknown mod conflict
