### ISSUE TITLE
[Bug]: create Train und Immersive Aircraft Bugs

### ISSUE THREAD

**Issue by IronDebiMan** [someaddons/betterchunkloading#18]
### Describe the bug you're experiencing

1.  The create train gets stuck with some of the blocks of the front the train turning invisible. When standing up from the seat the train moves through the player following its original course. 
2.  The create immersive aircraft vehicle gets stuck in flight, sometimes stuttering or just dropping the player to the ground. After relogging the player sits back in the flying vehicle.

### Reproducability

1. Using the create train contraption on a train track of around 500 block length or more as a passenger seated. 
1.1 The probability of the bug increases with increased render distance. Removing this mod alone solves the problem but also takes away the features of the mod.
2. Flying in an vehicle of create immersive aircraft.
![2024-04-05_18 02 30](https://github.com/someaddons/betterchunkloading/assets/114136013/e8d52636-07df-443b-8d8e-e26ac14eeede)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/IronDebiMan/6732fada5dddd901f09d4781bfaf2338

**Comment by someaddons** [comment]
probably fixed in 4.0, if not make a new report
