### ISSUE TITLE
[Bug]: mixin error with mod Very Many Players 

### ISSUE THREAD

**Issue by antoni0C0des** [someaddons/betterchunkloading#2]
### Describe the bug you're experiencing

I placed VMP and better chunk loading, and a mixin error happened!

### Reproducability

Just add both VMP and chunk loading and you can see the mixin error right before world load.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2, latest fabric loader version 0.14.22

### Modloader version

Fabric

### Logs

https://mclo.gs/pWTxdtZ (I can't make a gist rn, sorry)

**Comment by someaddons** [comment]
Not sure what vmp does there, but nothing I can really do here should ask vmp to fix it
