### ISSUE TITLE
[Bug]: Keeps overload my server

### ISSUE THREAD

**Issue by MbtMarco** [someaddons/betterchunkloading#20]
### Describe the bug you're experiencing

I installed on my server but it's probably incompatible with some mods because it keeps overload my server. 
(Maybe [First Person](https://modrinth.com/mod/first-person-model))

### Reproducability

Well, I use this mod in my own modpack so it is difficult to test it, you would have to install the mods in a dedicated server, I am available to send the modpack or the list of mods if needed.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://mclo.gs/CJCwcLq

**Comment by MbtMarco** [comment]
And yes, I tried it without C2ME but the mod still overload my server.

**Comment by someaddons** [comment]
Can't reproduce it, you may be simply loading nongenerated chunks in a pack which has slow worldgen, or some other mod is interferring

**Comment by MbtMarco** [comment]
Maybe C2ME?

**Comment by someaddons** [comment]
nah I did test with and without c2me, I am going to release an update adding better compatibility with c2me though
