### ISSUE TITLE
[Bug]: Ocean chunks bug

### ISSUE THREAD

**Issue by MbtMarco** [someaddons/betterchunkloading#21]
### Describe the bug you're experiencing

While using the boat after a few chunks this starts to happen: 

![2024-04-30_22 02 06](https://github.com/someaddons/betterchunkloading/assets/124934175/5cea9378-4df9-4fdf-9abf-03587c774c46)

I know it can be a normal function of the mod but if I try to enter those unloaded chunks the game starts to give some weird issues, also I don't know if it's a problem with your mod but after a few minutes in the ocean the RAM starts to ‘fill up’ like crazy.

### Reproducability

1) Take a boat

2) Go ahead in the ocean for 2 min

3) Look at the RAM while on the ocean and try to go in a unloaded chunk

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

https://mclo.gs/VIJp8u7

**Comment by MbtMarco** [comment]
A crash report:
https://mclo.gs/aLaLr1F

**Comment by someaddons** [comment]
the log looks more like a lithium or c2me issue, should report it to them

**Comment by MbtMarco** [comment]
I tried C2ME without Better Chunk Loading and it doesn't seem to cause any problems, I'll update you in the following days after doing more tests.

**Comment by someaddons** [comment]
cannot reproduce it at all using a big pack like prominence II 🤷 maybe try without c2me?

**Comment by MbtMarco** [comment]
I am closing this issue because the problem may it is caused by another mod, I will try when I have more time to test each single mod to understand if there is any incompatibility
