### ISSUE TITLE
[Request]: Forge 1.20.2 Support

### ISSUE THREAD

**Issue by DThaiPome** [someaddons/betterchunkloading#22]
### Describe the bug you're experiencing

This isn't a bug, just putting this here to request a build for Forge on Minecraft v1.20.2 :) 

### Reproducability

NA

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.2

### Modloader version

Forge

### Logs

NA

**Comment by someaddons** [comment]
next version is going to be 1.21, the intermediary versions are too small and already dying
