### ISSUE TITLE
[Bug]: Dragon Egg Dupe doesn't work more than once after Better Chunk Loading 4.0 Minecraft 1.20.1

### ISSUE THREAD

**Issue by AndreCelso** [someaddons/betterchunkloading#23]
### Describe the bug you're experiencing

Tried to dupe the dragon egg with fences below the portal, when the egg enter the portal, when i go to the end to collect it, it disappears.
P.S: It works once and then stops working

### Reproducability

Attempt to dupe the Dragon Egg more than once with any version of Better Chunk Loading after 4.0 in Minecraft 1.20.1 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/AndreCelso/78fcaf7cbfce7c53af0cb1c28babb509

**Comment by someaddons** [comment]
Its probably because betterchunkloading is a bit lazier with unloading and does unload right away. Anyway I've got no intention to support dupes, even if they're present in vanilla so not gonna fix this
