### ISSUE TITLE
[Bug]: Deadlock

### ISSUE THREAD

**Issue by KostromDan** [someaddons/betterchunkloading#24]
### Describe the bug you're experiencing

Just created new world, wandered around 2-3 mins and deadlock happened.

### Reproducability

Can't reproduce on same seed, seems like random.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19.2

### Modloader version

Forge

### Logs

https://gist.github.com/KostromDan/38407e2d7929fc1ed0c0fed159fb2c62

![image](https://github.com/someaddons/betterchunkloading/assets/90044015/0186bb34-34c4-410e-8ae5-af7b6a05afd7)

**Comment by someaddons** [comment]
Not really betterhcunkloadings fault, as it just queries a nearby chunk on the server thread during post load ticking of blocks(water ticking to make it start flow e.g.). Vanilla does the same thing, betterchunkloading just delays it a bit.

Its probably some of the worldgen mods in play causing the issue, like structure or biome mods.

What I can do is reducing the amount of possible unloaded chunk requests on a tick, which may give it less of a likelyhood to appear/stalls the server thread for less time

**Comment by someaddons** [comment]
improved in 4.3
