### ISSUE TITLE
[Bug]: game crashes with lithium while the player is moving

### ISSUE THREAD

**Issue by Mr-Squid42** [someaddons/betterchunkloading#26]
### Describe the bug you're experiencing

launched up a world with both lithium and betterchunkloading, while moving through the world, the game crashed.

### Reproducability

moving through a world in a instance with lithium

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21

### Modloader version

Fabric

### Logs

https://gist.github.com/Mr-Squid42/252cd43da4d34c39b70da77feaec89e1

**Comment by someaddons** [comment]
lithium causes this crash by changing vanilla code, all better chunk loading does it calling that code. Report to lithium

**Comment by Mr-Squid42** [comment]
ok, thanks
