### ISSUE TITLE
[Bug/Incompatability]: Game Crashes When Accompanied With "Chunks Fade In" Mod

### ISSUE THREAD

**Issue by wumil** [someaddons/betterchunkloading#27]
### Describe the bug you're experiencing

Game crashes when loading new chunks with BetterChunk and ChunksFadeIn.

ChunksFadeIn: https://www.curseforge.com/minecraft/mc-mods/chunks-fade-in

### Reproducability

Start a world with both mods enabled. Sprint to unloaded chunks.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21

### Modloader version

Fabric

### Logs

https://gist.github.com/wumil/507323c9aa94508f2df6ab98da624ec3

**Comment by someaddons** [comment]
lithium causes this crash by changing vanilla code, all better chunk loading does it calling that code. Report to lithium
