### ISSUE TITLE
Occasional deadlock loading a Quark crab

### ISSUE THREAD

**Issue by quat1024** [someaddons/betterchunkloading#29]
### Describe the bug you're experiencing

For the past while, both in 1.19 and 1.20, users have been reporting an occasional server deadlock when loading a Quark crab, which calls `Crab#updateDynamicGameEventListener` https://github.com/VazkiiMods/Quark/issues/4714. The commonality between these reports is they *all* have Smooth Chunk Save and Better Chunk Loading installed.

To the best of my knowledge, crab code for listening to nearby jukeboxes is exactly the same as Allay code for listening to nearby jukeboxes https://github.com/VazkiiMods/Quark/blob/8c9ec1b6b43a2dee2b57148a4972f2b9d29d66c3/src/main/java/org/violetmoon/quark/content/mobs/entity/Crab.java#L154-L157, and I have never heard of this issue happening without these mods installed, so I don't think quark is doing anything unusual here.

### Reproducability

Apparently u just hang occasionally

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19 - 1.20

### Modloader version

Forge

### Logs

https://github.com/VazkiiMods/Quark/issues/4714

**Comment by someaddons** [comment]
hm quite odd, those crashes are from the crab accessing an unloaded chunk. The only thing I could think off that may cause an issues is the `enableFasterChunkTasks` config option, might be worth trying to disable that
