### ISSUE TITLE
[Bug]: Mod not making any noticeable difference in chunk loading speed (1.18.2)

### ISSUE THREAD

**Issue by Mqony** [someaddons/betterchunkloading#3]
### Describe the bug you're experiencing

The mod has almost no effect on chunk loading speed with any more than 50 mods installed. Chunks still sadly take several seconds to load and I can literally fly into the void using just creative flight. I have a gen 4 ssd and i7 12700k processor so hardware isn't an issue, is there anything that can fix this issue?

### Reproducability

Install this mod alongside around 50 or more mods. Chunk loading is extremely slow.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.2

### Modloader version

Forge

### Logs

N/A

**Comment by someaddons** [comment]
it doesnt really speed up chunk loading itself much(it does but just a bit, may not be that noticeable) but starts generating the chunks earlier ahead of the player, the chunks itself pretty much still take just as long to load they just start a bit earlier.
