### ISSUE TITLE
[Bug]: Issues with generation of mushrooms, etc.

### ISSUE THREAD

**Issue by Mechalopa** [someaddons/betterchunkloading#30]
### Describe the bug you're experiencing

![2024-08-30_10 57 32](https://github.com/user-attachments/assets/65b621d2-4ae0-48de-8612-0a4760824ae6)
![2024-08-30_10 59 20](https://github.com/user-attachments/assets/9e8211d0-fbbf-4fea-abce-1f38d6ebbfc1)
When better chunk loading is installed, some blocks appear to be generated only on the client in places where they are not originally generated. (just like the Minecraft bugs of the past...)
It is noticeable in mushrooms and rare in short grass and small flowers.
They disappear when the block is updated.

### Reproducability

Look at swamp biome.

### Mod up to date

- [x] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1( also 1.21 / 1.20.1)

### Modloader version

NeoForge-21.1.31

### Logs

https://gist.github.com/Mechalopa/cd240f1597e06aec775d5da7807b7490

**Comment by someaddons** [comment]
fixed in the newest
