### ISSUE TITLE
[Bug]: Extremely long tick times while installed

### ISSUE THREAD

**Issue by ByThePowerOfScience** [someaddons/betterchunkloading#31]
### Describe the bug you're experiencing

With this mod installed, tick times while generating chunks skyrocket to several minutes each.  I opened the client up in IDEA's debugger, and all of the time is being spent in chunk generation.  Nothing weird in the callstack (except that only one worker thread was active, now that I think about it), it's just the chunk generation taking forever even for vanilla biomes.  The issue vanishes immediately after uninstalling the mod.

### Reproducability

Use this modpack: 
[epochS2.zip](https://github.com/user-attachments/files/17237760/epochS2.zip)

Load a new world with default settings, and attempt to generate chunks.  The tick loop should freeze as the server thread blocks to wait for the chunk generation.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

[will do, just saving issue first]

**Comment by someaddons** [comment]
can't reproduce it, probably not enough ram assigned and you did not use the up to date version (4.5)

**Comment by ByThePowerOfScience** [comment]
> can't reproduce it, probably not enough ram assigned and you did not use the up to date version (4.5)

Using 16 GB of RAM on the server when the problem presents itself serverside (only 10GB is consumed during the issue), and 8 GB of RAM on the client when reproduced in singleplayer.  

The CF comments show many others have had the same problem we are, would you mind trying with a few more worlds? Default generation, structures on.
