### ISSUE TITLE
[Bug]: Mod makes my game crash when jumping with elyta

### ISSUE THREAD

**Issue by sapphiVy** [someaddons/betterchunkloading#33]
### Describe the bug you're experiencing

Whenever i do a timed jumping while gliding with the elytra, I'm able to do a weird hop but after that my game crashes

### Reproducability

I start gliding with the elytra, then time a jump right when I'm about to hit the ground and then game crashes

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Fabric

### Logs

https://gist.github.com/sapphiVy/03542de5b754121e8887f67f38f06923

**Comment by someaddons** [comment]
https://github.com/someaddons/betterchunkloading/issues/28
Lithium is crashing
