### ISSUE TITLE
[Bug]: crash with lithium

### ISSUE THREAD

**Issue by VaporeonScripts** [someaddons/betterchunkloading#34]
### Describe the bug you're experiencing

crash due to ticking player (neoforge 1.21.1)

### Reproducability

install this mod along lithium

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21.1

### Modloader version

Forge

### Logs

https://mclo.gs/hEiCnIg

**Comment by someaddons** [comment]
https://github.com/someaddons/betterchunkloading/issues/28
Lithium is crashing
