### ISSUE TITLE
[Bug]: buggy generation of mushrooms 

### ISSUE THREAD

**Issue by kuba26038** [someaddons/betterchunkloading#35]
### Describe the bug you're experiencing

it turns out that whenever i use this mod, there's some mushrooms that spawn where they shouldn't spawn [e.g. in broad daylight], they are immediately destroyed and this results in loads of mushrooms just laying around everywhere (in the past i also had a similar issue where they spawned in broad daylight, and for some reason instead of being immediately destroyed they became indestructible ghost blocks, but i can't replicate that).

### Reproducability

1- launch the game with this mod installed
2- find a place where mushrooms normally spawn in the shadows of some trees
3- observe the mushroom items that have no buisness lying around everywhere and yet they do

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://pastebin.com/S98hA6v9

**Comment by someaddons** [comment]
Which mod version are you playing? that should've been fixed in 4.5

**Comment by kuba26038** [comment]
It certainly is 4.5 for 1.20.1

**Comment by someaddons** [comment]
fixed in 5.1
