### ISSUE TITLE
[Bug]: Chunks simply dont load.

### ISSUE THREAD

**Issue by mateus3c** [someaddons/betterchunkloading#5]
### Describe the bug you're experiencing

Im playing on a huge modpack and when I add Better Chunk Loading my game wont load any chunks besides the ones generated after I join the world (the first 14 chunks, since I'm playing with render dist at 14). I'll try to provide organized and complete data to help us figure out what might have happened.

The issue only happens when Better Chunk Loading is present, removing it from the mods folder fixes the issue, and re-adding it to the mods folder makes the issue happen again.
I have made all tests on the exact same world seed, I have recreated the same world on every test. There's half village generated on the first 14 chunks.

People that tried to help me pointed out that Random Village Names could be the one causing issues, but removing it and keeping Better Chunk Loading didn't fix the issue, either way I have also collected data with and without Random Village Names.

After each /spark I have also made a /sparkclient. 

**Data _WITH_ Better Chunk Loading installed.**
/spark profiler start --thread * --timeout 120: https://spark.lucko.me/vhLfwtAlcN
/sparkclient profiler start --thread * --timeout 120: https://spark.lucko.me/ljKNw0eiQe
[with_BetterChunkLoading.log](https://github.com/someaddons/betterchunkloading/files/13696455/with_BetterChunkLoading.log)
[with_BetterChunkLoading_console.log](https://github.com/someaddons/betterchunkloading/files/13696456/with_BetterChunkLoading_console.log)

**Data _WITH_ Better Chunk Loading installed + Random Village Names.**
/spark profiler start --thread * --timeout 120: https://spark.lucko.me/FYrPgxCuPL
/sparkclient profiler start --thread * --timeout 120: https://spark.lucko.me/S7ZEnWZ4lh
[with_BetterChunkLoading + Random Village Names.log](https://github.com/someaddons/betterchunkloading/files/13696353/with_BetterChunkLoading.%2B.Random.Village.Names.log)
[with_BetterChunkLoading + Random Village Names_console.log](https://github.com/someaddons/betterchunkloading/files/13696354/with_BetterChunkLoading.%2B.Random.Village.Names_console.log)

**Data _WITHOUT_ Better Chunk Loading installed.**
/spark profiler start --thread * --timeout 120: https://spark.lucko.me/FLttZfJbOz
/sparkclient profiler start --thread * --timeout 120: https://spark.lucko.me/KYEdUXO4N3
[without_BetterChunkLoading.log](https://github.com/someaddons/betterchunkloading/files/13696522/without_BetterChunkLoading.log)
[without_BetterChunkLoading_console.log](https://github.com/someaddons/betterchunkloading/files/13696523/without_BetterChunkLoading_console.log)

**Data _WITHOUT_ Better Chunk Loading installed + Random Village Names.**
/spark profiler start --thread * --timeout 120: https://spark.lucko.me/VIqbySeaZw
/sparkclient profiler start --thread * --timeout 120: https://spark.lucko.me/MfBGcmUu4u
[without_BetterChunkLoading + Random Village Names.log](https://github.com/someaddons/betterchunkloading/files/13696340/without_BetterChunkLoading.%2B.Random.Village.Names.log)
[without_BetterChunkLoading + Random Village Names_console.log](https://github.com/someaddons/betterchunkloading/files/13696342/without_BetterChunkLoading.%2B.Random.Village.Names_console.log)

### Reproducability

(Already Described)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/mateus3c/63c1c9b4741a6dce27d5ac80bf9f9bd6

**Comment by someaddons** [comment]
I've got no issue in my own modpacks, so this is most likely some mod conflict with another mod.

Your spark seems to indicatate that the server is stuck trying to load chunks for the mod which adds an anthill, as that accessed some unloaded area
![image](https://github.com/someaddons/betterchunkloading/assets/38401808/c5bb4150-51fb-4c07-80d1-c105382ec62c)

Your latest.log link doesnt work

**Comment by mateus3c** [comment]
but why would that antihill block (from the Spawn mod) conflict with Better Chunk Loading?  It doesn't make much sense for me why removing Better Chunk Loading fixes the issue

**Comment by someaddons** [comment]
I'm not sure its the anthill mod, might be any other mod aswell

**Comment by mateus3c** [comment]
So there isn't a way to discover which mod is causing this weird behavior on Better Chunk Loading?

**Comment by someaddons** [comment]
there is, testing
copy the world before, remove half the mods see if it works. If yes the put back the mods you removed piece by piece and see which failed, if not remove the half of the remaining again^^

The anthill mod is just the first one I'd test, since it did show up on the report

**Comment by mateus3c** [comment]
I have made that, I actually spend **many** hours doing this, that's when I found the only mod causing this issue was Better Chunk Loading, I thought it was strange and kept removing and readding mods but the issue really only happened when Better Chunk Loading was present

**Comment by SiverDX** [comment]
The combination of betterchunkloading and [this](https://www.curseforge.com/minecraft/mc-mods/spawn-mod) does seem to lead to a server deadlock

this part in particular
https://github.com/N1nn1/spawn/blob/d3402df54951d521edc7beca1ac8f33c8dc4b730/src/main/java/com/ninni/spawn/block/entity/AnthillBlockEntity.java#L208C36-L208C46

might be unloaded chunk (do block entities in unloaded chunks get ticked?), might also betterchunkloading just not wanting to load something (prioritizing the player etc.)

**Comment by someaddons** [comment]
Tried it with spawn and couldnt reproduce the issue either and works for me on server/other modpacks aswell. So it is for sure a mod conflict, but without knowing which or at least getting me a modlist/seed to reproduce it theres nothing I can do

**Comment by mateus3c** [comment]
I wont be able to make that for a while because Im on vacation but when I get home I will. But the mod list can be found on the log, the "Mod Optimizer" mod writes all the mods presented.

another thing: I haven't found any way to ask questions to you but I wanted to know if you will upload your mods on Modrinth?

**Comment by someaddons** [comment]
try version 3.0

**Comment by someaddons** [comment]
open a new one if still got issues
