### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xKiLrD34TH** [someaddons/betterchunkloading#6]
### Describe the bug you're experiencing

Water source blocks failing to update and flow during generation. (Haven't seen if lava does the same.) When better gen is removed water will update and flow as it should when regenerating the same seed. 

### Reproducability

Upon world creation, lakes, aquifers and other static bodies of water don't flow and just more or less float. I find it regularly in caverns underground. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

n/a

**Comment by someaddons** [comment]
They're just delayed, they should update after a minute or so

**Comment by someaddons** [comment]
fixed
