### ISSUE TITLE
[Bug]: Chunks barely get loaded

### ISSUE THREAD

**Issue by or1n** [someaddons/betterchunkloading#7]
### Describe the bug you're experiencing

When i Install the mod on my server with the standard config new chunks barely get loaded and the CPU goes into overdrive. I've tried tinkering with the settings, but nothing helps.

minecraft 1.20.1
Forge 47.0.35

Mods:
AdvancementPlaques-1.20.1-forge-1.5.1.jar
AI-Improvements-1.20-0.5.2.jar
alternate_current-mc1.20-1.7.0.jar
appleskin-forge-mc1.20.1-2.5.1.jar
architectury-9.1.12-forge.jar
AttributeFix-Forge-1.20.1-21.0.3.jar
balm-forge-1.20.1-7.1.4.jar
BetterCompatibilityChecker-neo-4.0.8+mc1.20.1.jar
biggerstacks-1.20.1-1.0.0-all.jar
BoatBreakFix-Universal-1.0.2.jar
Bookshelf-Forge-1.20.1-20.1.6.jar
Bossominium-18.2-1.20.1.jar
caelus-forge-3.1.0+1.20.jar
canary-mc1.20.1-0.2.7.jar
chunkloaders-1.2.8a-forge-mc1.20.1.jar
citadel-2.4.9-1.20.1.jar
clickadv-1.20.1-3.6.jar
cloth-config-11.1.106-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
collective-1.20.1-7.23.jar
colytra-forge-6.2.2+1.20.1.jar
connectivity-1.20.1-4.6.jar
corpse-1.20.1-1.0.5.jar
cosmeticarmorreworked-1.20.1-v1a.jar
Craftable+Enchanted+Golden+Apple+(1.20.1).jar
Craftable+Horse+Armors+(1.20.1).jar
cupboard-1.20.1-2.1.jar
curios-forge-5.4.5+1.20.1.jar
customizableelytra-forge-2.1.1+1.20 (1).jar
DeathFinder-v8.0.1-1.20.1-Forge.jar
easyelytratakeoff-1.20.1-4.1.jar
elytraslot-forge-6.3.0+1.20.1.jar
Exchangers-1.20.1-3.5.1.jar
exposure-1.20.1-1.1.1.jar
farsighted-mobs-forge-1.1-1.20.1.jar
fastestportalsforge-1.0.4.jar
FastFurnace-1.20.1-8.0.1.jar
FastLeafDecay-31.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
FastWorkbench-1.20.1-8.0.2.jar
ferritecore-6.0.1-forge.jar
flatbedrock-forge-3.0.1-build.18+mc1.20.1.jar
forgery-3.4.4+1.20.jar
FriendlyFire-Forge-1.20.1-18.0.5.jar
ftb-essentials-forge-2001.2.2.jar
ftb-library-forge-2001.1.4.jar
geckolib-forge-1.20.1-4.2.3.jar
getittogetherdrops-forge-1.20-1.3.jar
gml-4.0.9-all.jar
gpumemleakfix-1.20.1-1.6.jar
grassseeds-1.20.1-3.1.jar
GunpowderLib-1.20.2-2.2.1.jar
Iceberg-1.20.1-forge-1.1.16.jar
inventorytotem-1.20.1-3.1.jar
Jade-1.20.1-forge-11.6.3.jar
leaky-1.20.1-1.7.jar
letmedespawn-forge-1.20.x-1.2.0.jar
Log-Begone-Forge-1.20.1-1.0.8.jar
L_Enders_Cataclysm-1.76+-1.20.1.jar
MaxHealthFix-Forge-1.20.1-12.0.2.jar
MobDespawnTimers-1.20.1-3.0.1.jar
modernfix-forge-5.1.1+mc1.20.1.jar
netherportalfix-forge-1.20-13.0.0.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
open-parties-and-claims-forge-1.20.1-0.20.1.jar
PassthroughSigns-1.20-2.6.2.jar
pathundergates-1.20.1-1.0.1-release.jar
Placebo-1.20.1-8.3.7.jar
Prism-1.20.1-forge-1.0.5.jar
puffish_skills-0.10.0-1.20-forge.jar
PuzzlesLib-v8.0.2-1.20.1-Forge.jar
quickstack-1.20.1-1.jar
rare-ice-0.6.0.jar
resourcefulconfig-forge-1.20.1-2.1.0.jar
resourcefullib-forge-1.20.1-2.1.19.jar
RoughlyEnoughItems-12.0.684-forge.jar
scarecrowsterritory-1.1.11d-forge-mc1.20.jar
ShinyHorses-1.20.1-1.2.jar
shulkerboxtooltip-forge-4.0.4+1.20.1.jar
smoothboot-mc1.20.1-0.0.3.jar
sophisticatedbackpacks-1.20.1-3.18.56.890.jar
sophisticatedcore-1.20.1-0.5.83.395.jar
starlight-1.1.2+forge.1cda73c.jar
structureessentials-1.20.1-3.2.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.15-forge-mc1.20.jar
trashslot-forge-1.20-15.1.0.jar
Vanishmod-1.20.1-1.1.14.jar
villagernames-1.20.1-7.1.jar
YungsApi-1.20-Forge-4.0.2.jar
YungsBetterEndIsland-1.20-Forge-2.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsBridges-1.20-Forge-4.0.3.jar
YungsExtras-1.20-Forge-4.0.3.jar

### Reproducability

Join the server with Better chunk loading installed.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/or1n/924632aa22e138a4949f7a7e75c41df4

**Comment by someaddons** [comment]
can you run with `-Dmixin.debug.verbose=true` as java/server start parameter? and post the latest.log into gist from that?

**Comment by someaddons** [comment]
try version 3.0
