### ISSUE TITLE
[Bug]: Crash on first launch with Pocketwatch on Fabric 1.20.1

### ISSUE THREAD

**Issue by Poopooracoocoo** [someaddons/betterchunkloading#9]
### Describe the bug you're experiencing

Crashes on launch with Pocketwatch on Fabric 1.20.1

Does not occur with subsequent launches.

### Reproducability

- Create a Fabric instance on 1.20.1
- Add Fabric API, Cupboard, Better Chunk Loading, owo lib, Pocketwatch

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

Minecraft 1.20.1

### Modloader version

Fabric

### Logs

https://gist.github.com/Poopooracoocoo/a839479c9ce1de2e480b9d67a6167ecb

**Comment by someaddons** [comment]
Thats an issue of pocketwatch failing on first launch(when its config is missing), reported here: https://github.com/Minenash/Pocketwatch/issues/10
